name: News Digest

on:
  schedule:
    - cron: "10 2 * * *"
    - cron: "10 14 * * *"
  workflow_dispatch:

jobs:
  send-digest:
    runs-on: ubuntu-latest
    environment: routine

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install -r requirements.txt

      - name: Run only in correct IST window
        run: python scheduler_guard.py

        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
          RECEIVER_MAIL: ${{ secrets.RECEIVER_MAIL }}
